"""
Figures and LaTeX table fragments for the manuscript, built only from the
stored outputs in results/temporal_design/. Reads JSON, fits nothing.

    python3 make_figures.py [--out DIR]     # default: results/temporal_design/paper

Writes:
  fig-stability-k.pdf      CV Nogueira stability vs k, days 30/60/90 and xAPI
  fig-holdout-cost.pdf     2014J holdout AUC(top-k) - AUC(all), cutoff x evaluator
  tab-data.tex             rows, features and pass rates per cutoff
  tab-stability.tex        grid and k <= p/3 stability means
  tab-rfe-contrasts.tex    RFE vs each method, CV estimate and Bonferroni interval
  tab-cross.tex            cross-presentation within / loss (all modules, n = 1,650)
  tab-holdout-all.tex      CV vs holdout AUC with all features, per evaluator
  tabS_*.tex               supplementary tables
"""
import os
import json
import argparse
from itertools import combinations

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from paths import RESULTS_DIR

R = os.path.join(RESULTS_DIR, "temporal_design")
M = ["ANOVA", "SHAP", "MI", "LASSO", "RFE"]
DAYS = [30, 60, 90]
K_GRID = [5, 10, 15, 20, 25, 30]
EV = {"xgb": "XGBoost", "rf": "Random forest", "lr": "Logistic regression"}
PAIRS = ["2013B|2013J", "2013B|2014B", "2013J|2014B", "2013B|2014J", "2013J|2014J", "2014B|2014J"]
STYLE = {"ANOVA": ("tab:blue", "o"), "SHAP": ("tab:orange", "s"), "MI": ("tab:green", "^"),
         "LASSO": ("tab:purple", "D"), "RFE": ("tab:red", "v")}


def load(name):
    with open(os.path.join(R, name)) as f:
        return json.load(f)


def diff(d, a, b):
    """Return (estimate, record) for a - b from a bootstrap 'diff' block stored as x_minus_y."""
    if f"{a}_minus_{b}" in d:
        return 1, d[f"{a}_minus_{b}"]
    return -1, d[f"{b}_minus_{a}"]


def fig_stability(out):
    sets = [(f"Day {d}", f"oulad_day{d}_analysis.json") for d in DAYS] + [("xAPI (end of term)", "xapi_endofterm_analysis.json")]
    fig, axes = plt.subplots(1, 4, figsize=(13, 3.2), sharey=True)
    for ax, (title, fn) in zip(axes, sets):
        a = load(fn)
        curve = a["stability_curve_nogueira"]
        p = a["n_features"]
        ks = [k for k in range(1, 31)]
        for m in M:
            c, mk = STYLE[m]
            ax.plot(ks, [curve[m][str(k)] for k in ks], color=c, lw=1.4, label=m)
            ax.plot(K_GRID, [curve[m][str(k)] for k in K_GRID], ls="none", marker=mk, color=c, ms=4)
        ax.axvline(p // 3, color="grey", ls=":", lw=1)
        ax.set_title(f"{title} (p = {p})", fontsize=10)
        ax.set_xlabel("k (features kept)")
        ax.set_xlim(1, 30)
    axes[0].set_ylabel("Nogueira stability (CV)")
    axes[0].legend(fontsize=8, loc="lower left")
    fig.tight_layout()
    fig.savefig(os.path.join(out, "fig-stability-k.pdf"))
    plt.close(fig)


def fig_holdout(out):
    fig, axes = plt.subplots(3, 3, figsize=(11, 8), sharex=True)
    for i, d in enumerate(DAYS):
        h = load(f"oulad_day{d}_holdout.json")
        for j, ev in enumerate(EV):
            ax = axes[i, j]
            base = h["baseline_all"][ev]["roc_auc"]
            for m in M:
                c, mk = STYLE[m]
                y = np.array([h["methods"][m]["per_k"][str(k)][ev]["roc_auc"] - base for k in K_GRID])
                ci = np.array([h["bootstrap"][f"{ev}_k{k}"]["diff_vs_all_ci"][m] for k in K_GRID])
                ax.errorbar(K_GRID, y, yerr=[y - ci[:, 0], ci[:, 1] - y], color=c, marker=mk, ms=3.5,
                            lw=1.2, capsize=2, label=m)
            ax.axhline(0, color="grey", lw=0.8)
            if i == 0:
                ax.set_title(EV[ev], fontsize=10)
            if j == 0:
                ax.set_ylabel(f"Day {d}\nAUC(top-k) - AUC(all)")
            if i == 2:
                ax.set_xlabel("k (features kept)")
    axes[0, 0].legend(fontsize=7, loc="lower right")
    fig.tight_layout()
    fig.savefig(os.path.join(out, "fig-holdout-cost.pdf"))
    plt.close(fig)


def write(out, name, body):
    with open(os.path.join(out, name), "w") as f:
        f.write("% generated by code/scripts/make_figures.py; do not edit by hand\n" + body)


def tab_data(out):
    rows = []
    for d in DAYS:
        a, h = load(f"oulad_day{d}_analysis.json"), load(f"oulad_day{d}_holdout.json")
        cc = load(f"oulad_day{d}_cross_cohort.json")
        comp = [json.loads(l)["composition"] for l in open(os.path.join(R, f"oulad_day{d}_cross_cohort.jsonl"))][0]
        rows.append(f"Day {d} & {h['n_dev']:,} & {h['n_holdout']:,} & {a['n_features']} & "
                    f"{h['dev_pass_rate']:.3f} & {h['holdout_pass_rate']:.3f} & {a['dates_used']['max_assess_date']:.0f} \\\\")
    write(out, "tab-data.tex", "\n".join(rows) + "\n")


def tab_stability(out):
    rows = []
    for title, fn in [(f"Day {d}", f"oulad_day{d}_analysis.json") for d in DAYS] + [("xAPI", "xapi_endofterm_analysis.json")]:
        ks = load(fn)["k_summaries_nogueira"]
        rows.append(title + " & " + " & ".join(f"{ks['grid']['mean'][m]:.3f} ({ks['k_le_p3']['mean'][m]:.3f})" for m in M) + " \\\\")
    write(out, "tab-stability.tex", "\n".join(rows) + "\n")


def tab_rfe(out, settings=None, name="tab-rfe-contrasts.tex"):
    rows = []
    settings = settings or [(f"Day {d}", f"oulad_day{d}_bootstrap_summary.json") for d in DAYS] + \
        [("xAPI", "xapi_endofterm_bootstrap_summary.json")]
    for title, fn in settings:
        g = load(fn)["summaries"]["grid"]["diff"]
        cells = []
        for m in ["ANOVA", "SHAP", "MI", "LASSO"]:
            s, r = diff(g, "RFE", m)
            lo, hi = sorted(s * np.array(r["ci_bonferroni"]))
            mark = "$^{*}$" if r["robust_bonferroni"] else ""
            cells.append(f"${s * r['estimate_cv']:+.3f}${mark} [{lo:+.2f}, {hi:+.2f}]")
        hw = [(v["ci_bonferroni"][1] - v["ci_bonferroni"][0]) / 2 for k, v in g.items() if "RFE" not in k]
        rows.append(f"{title} & " + " & ".join(cells) + f" & {min(hw):.3f}--{max(hw):.3f} \\\\")
    write(out, name, "\n".join(rows) + "\n")


def tab_cross(out, suffix="", name="tab-cross.tex"):
    rows = []
    for key, label in [("within_dev_dev", "Within a presentation"), ("loss_dev_dev", "Loss, development pairs"),
                       ("loss_dev_2014J", "Loss, pairs with 2014J")]:
        cells = []
        for m in M:
            cells.append(" / ".join(f"{load(f'oulad_day{d}_cross_cohort{suffix}.json')['summaries']['grid'][key][m]['mean']:.2f}"
                                    for d in DAYS))
        rows.append(f"{label} & " + " & ".join(cells) + " \\\\")
    cells = [" / ".join(str(load(f"oulad_day{d}_cross_cohort{suffix}.json")["loss_positive"]["grid"][m]["pairs_with_mean_loss_gt0"])
                        for d in DAYS) for m in M]
    rows.append("Pairs with mean loss $>0$ (of 6) & " + " & ".join(cells) + " \\\\")
    write(out, name, "\n".join(rows) + "\n")


def tab_holdout_all(out):
    rows = []
    for d in DAYS:
        a, h = load(f"oulad_day{d}_analysis.json"), load(f"oulad_day{d}_holdout.json")
        rows.append(f"Day {d} & " + " & ".join(f"{a['baseline_all'][ev]['roc_auc']['mean']:.3f} / {h['baseline_all'][ev]['roc_auc']:.3f}"
                                              for ev in EV) + " \\\\")
    write(out, "tab-holdout-all.tex", "\n".join(rows) + "\n")


def tabS_k_le_p3(out):
    rows = []
    for title, fn in [(f"Day {d}", f"oulad_day{d}_bootstrap_summary.json") for d in DAYS] + [("xAPI", "xapi_endofterm_bootstrap_summary.json")]:
        for summ in ["grid", "k_le_p3"]:
            g = load(fn)["summaries"][summ]["diff"]
            hits = [f"{k.replace('_minus_', '$-$')} ${v['estimate_cv']:+.3f}$" + ("$^{*}$" if v["robust_bonferroni"] else "")
                    for k, v in g.items() if v["robust"]]
            label = "grid" if summ == "grid" else "$k\\le p/3$"
            rows.append(f"{title} & {label} & " + ("; ".join(hits) or "none") + " \\\\")
    write(out, "tabS-contrasts.tex", "\n".join(rows) + "\n")


def tabS_cross_pairs(out):
    rows = []
    for suffix, mode in [("", "All modules"), ("_common", "Common modules")]:
        for d in DAYS:
            j = load(f"oulad_day{d}_cross_cohort{suffix}.json")
            g, lp = j["summaries"]["grid"], j["loss_positive"]["grid"]
            for pr in PAIRS:
                rows.append(f"{mode}, day {d} & {pr.replace('|', '--')} & " + " & ".join(
                    f"${g['loss_' + pr][m]['mean']:+.3f}$ ({lp[m]['share_of_repeats'][pr]:.2f})" for m in M) + " \\\\")
            rows.append("\\addlinespace")
    write(out, "tabS-cross-pairs.tex", "\n".join(rows) + "\n")


def tabS_lag(out):
    rows = []
    for d in [30, 60]:
        for lag in ["", "_tmalag14"]:
            ks = load(f"oulad_day{d}{lag}_analysis.json")["k_summaries_nogueira"]["grid"]["mean"]
            rows.append(f"Day {d}, lag {'14' if lag else '0'} & " + " & ".join(f"{ks[m]:.3f}" for m in M) + " \\\\")
    write(out, "tabS-lag.tex", "\n".join(rows) + "\n")


def tabS_cv_auc(out):
    rows = []
    for d in DAYS:
        a = load(f"oulad_day{d}_analysis.json")
        for k in K_GRID:
            r = a["per_k"][str(k)]["roc_auc"]
            rows.append(f"Day {d} & {k} & " + " & ".join(f"{r[m]['xgb']['mean']:.3f}" for m in M) + " \\\\")
        n_sig = {ev: sum(v["p_adjusted_bh"] is not None and v["p_adjusted_bh"] < 0.05
                         for k in K_GRID for v in a["per_k"][str(k)]["pairwise_roc_auc"][ev].values()) for ev in EV}
        rows.append(f"\\multicolumn{{7}}{{l}}{{\\footnotesize Day {d}: BH-significant pairs of 60 --- "
                    + ", ".join(f"{EV[ev]} {n}" for ev, n in n_sig.items()) + "}\\\\\\addlinespace")
    write(out, "tabS-cv-auc.tex", "\n".join(rows) + "\n")


def tabS_bias(out):
    rows = []
    for title, fn in [(f"Day {d}", f"oulad_day{d}_bootstrap_summary.json") for d in DAYS] + [("xAPI", "xapi_endofterm_bootstrap_summary.json")]:
        st = load(fn)["summaries"]["grid"]["stability"]
        rows.append(f"{title} & " + " & ".join(f"{st[m]['estimate_cv']:.3f} / {st[m]['bias']:+.3f} / {st[m]['se']:.3f}" for m in M) + " \\\\")
    write(out, "tabS-bias.tex", "\n".join(rows) + "\n")


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=os.path.join(R, "paper"))
    out = ap.parse_args().out
    os.makedirs(out, exist_ok=True)
    fig_stability(out)
    fig_holdout(out)
    tab_data(out)
    tab_stability(out)
    tab_rfe(out)
    # RFE contrasts with a 14-day TMA marking lag (stability_bootstrap.py --tma-lag 14).
    tab_rfe(out, [(f"Day {d}, lag {lag}", f"oulad_day{d}_bootstrap_summary.json" if not lag else
                   os.path.join("lag14_boot", f"oulad_day{d}_tmalag14_bootstrap_summary.json"))
                  for d in [30, 60] for lag in [0, 14]], "tabS-lag-contrasts.tex")
    tab_cross(out)
    tab_cross(out, "_common", "tabS-cross-common.tex")
    tab_holdout_all(out)
    tabS_k_le_p3(out)
    tabS_cross_pairs(out)
    tabS_lag(out)
    tabS_cv_auc(out)
    tabS_bias(out)
    print("wrote", sorted(os.listdir(out)))
